# Generated by Django 5.2.6 on 2025-09-04 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0003_grupo_membrogrupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacaNiquel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recompensa', models.CharField(choices=[('10_reais', '💰 R$ 10,00'), ('5_reais', '💵 R$ 5,00'), ('vale_trabalho', '📝 Vale-trabalho'), ('doce', '🍭 Doce'), ('salgado', '🥨 Salgado')], max_length=20, verbose_name='Recompensa')),
                ('data_jogada', models.DateTimeField(auto_now_add=True, verbose_name='Data da Jogada')),
                ('resgatado', models.BooleanField(default=False, verbose_name='Resgatado')),
                ('data_resgate', models.DateTimeField(blank=True, null=True, verbose_name='Data do Resgate')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.aluno', verbose_name='Aluno')),
                ('resgatado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resgatado por')),
            ],
            options={
                'verbose_name': 'Caça-níquel',
                'verbose_name_plural': 'Caça-níquel',
                'ordering': ['-data_jogada'],
            },
        ),
    ]
