# Generated by Django 5.2.6 on 2025-09-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0004_cacaniquel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to='gamificacao.aluno', verbose_name='Líder do Grupo'),
        ),
    ]
